name: Generate Snake GIF

on:
  schedule:
    - cron: "0 0 * * *" # รันอัปเดตทุกวัน
  workflow_dispatch:     # กดรันเองได้ตลอดเวลา

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pillow

      - name: Generate GIF
        run: python snake.py

      - name: Commit and push GIF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.gif
          git commit -m "Update snake animation" || exit 0
          git push
